env: dev

tokens:
  access_secret: QZ8PVsIRj5SbSvjpMUp75fUzWydyQY4zXBvtoir532E=
  access_ttl: 15m
  refresh_secret: +1bKAkSTo3Iluk3g8pU0Fe45kLJf1zA6shjDbAAhk1I=
  refresh_ttl: 1h

server:
  port: 8080
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 1m
  max_header_bytes: 1048576 # 1 << 20

postgres:
  user: postgres
  password: postgres
  host: db
  port: 5432
  database: auth-service
  sslmode: disable
  max_conns: 20
  min_conns: 4
  max_conn_lifetime: 1h
  max_conn_idle_time: 30m
  health_check_period: 1m
  migrations_path: ./migrations
