services:
  db:
    image: postgres:17-alpine
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-auth-service}
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
    container_name: auth-service
    restart: unless-stopped
    ports:
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}
    volumes:
      - ./migrations:/migrations
      - ${CONFIG_PATH:-./config.yml}:/config.yml
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg-data:
    name: postgres_data
